package flightProject.flightBooking.flights;

public enum Airport
{
    HEATHROW,
    LAX,
    KOTOKA,
    SHAHJALAL_INTERNATIONAL_AIRPORT,
    LUTON,
    GATWICK,
    STANSTED,
    EL_PRAT_AIRPORT,
    MOHAMMED_V_INTERNATIONAL_AIRPORT,
    HOUARI_BOUMEDIENE_AIRPORT,
    TRIBHUVAN_INTERNATIONAL_AIRPORT,
    HONG_KONG_AIRPORT,
    CAPE_TOWN,
    COPENHAGEN
}
